<?php
$prefixes = '
@prefix cpm: <' . $this->siteConfig['model'] . 'cpd/> . \n
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . \n';

$personsQuery = $prefixes . 'SELECT *
WHERE {
	?resourceUri <' . $this->siteConfig['model'] . 'cpd/hasPeriod> ?period .
	?period <' . $this->siteConfig['model'] . 'cpd/periodBody> <'.$this->resourceUri.'> .
}';
$persons = $this->querylist( $personsQuery, 'local/items/liplain.phtml');
?>

<h2 class=""><?php echo $this->title ?></h2>

<?php
$bodyPlace = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->siteConfig['model'] . 'cpd/bodyPlace> ?resourceUri', 'template' => 'resource'));
if ( $bodyPlace != "" ) { ?>
	<p>Ort: <?php echo $bodyPlace; ?></p>
<?php } ?>

<?php if ( $persons != "" ) { ?>
	<div class="">
		<h3 class="">Studenten, Professoren, Mitarbeiter</h3>
		<?php echo $persons; ?>
	</div>
<?php } ?>