<?php
$prefixes = '
@prefix cpm: <' . $this->siteConfig['model'] . 'cpd/> . \n
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> . \n';

$bornQuery = $prefixes . 'SELECT *
WHERE {
	?resourceUri <' . $this->siteConfig['model'] . 'cpd/hasPeriod> ?period .
	?period rdf:type <' . $this->siteConfig['model'] . 'cpd/Birth> .
	?period <' . $this->siteConfig['model'] . 'cpd/periodPlace> <'.$this->resourceUri.'> .
}';
$born = $this->querylist( $bornQuery, 'local/items/liplain.phtml');

$bodiesQuery = $prefixes . 'SELECT *
WHERE {
	?resourceUri <' . $this->siteConfig['model'] . 'cpd/bodyPlace> ?period .
FILTER ( ?period = <'.$this->resourceUri.'> )
}';
$bodies = $this->querylist( $bodiesQuery, 'local/items/liplain.phtml');

?>

<h2 class=""><?php echo $this->title ?></h2>

<?php if ( $born != "" ) { ?>
	<div class="">
		<h3 class="">In <?php echo $this->title ?> geborene Personen</h3>
		<?php echo $born; ?>
	</div>
<?php } ?>

<?php if ( $bodies != "" ) { ?>
	<div class="">
		<h3 class="">Körperschaften in <?php echo $this->title ?></h3>
		<?php echo $bodies; ?>
	</div>
<?php } ?>
