<?php
$prefixes = '
PREFIX cpd: <' . $this->namespaces["cpd"] . '>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ';

$locatedInQuery = $prefixes . 'SELECT *
WHERE {
	<'.$this->resourceUri.'> <' . $this->namespaces["shv"] . 'isLocatedIn> ?resourceUri .
}';
$locatedIn = $this->querylist( $locatedInQuery, 'local/items/liplain.phtml');

$bornQuery = $prefixes . 'SELECT *
WHERE {
	?resourceUri <' . $this->namespaces["cpd"] . 'hasPeriod> ?period .
	?period rdf:type <' . $this->namespaces["cpd"] . 'Birth> .
	?period <' . $this->namespaces["cpd"] . 'periodPlace> <'.$this->resourceUri.'> .
}';
$born = $this->querylist( $bornQuery, 'local/items/liplain.phtml');

$diedQuery = $prefixes . 'SELECT *
WHERE {
	?resourceUri <' . $this->namespaces["cpd"] . 'hasPeriod> ?period .
	?period rdf:type <' . $this->namespaces["cpd"] . 'Death> .
	?period <' . $this->namespaces["cpd"] . 'periodPlace> <'.$this->resourceUri.'> .
}';
$died = $this->querylist( $diedQuery, 'local/items/liplain.phtml');

$bodiesQuery = $prefixes . 'SELECT *
WHERE {
	?resourceUri <' . $this->namespaces["cpd"] . 'bodyPlace> ?period .
FILTER ( ?period = <'.$this->resourceUri.'> )
}';
$bodies = $this->querylist( $bodiesQuery, 'local/items/liplain.phtml');

?>

<h2 class=""><?php echo $this->title ?></h2>

<?php if ( $locatedIn != "" ) { ?>
	<div class="">
		<p>Liegt in: <?php echo $locatedIn; ?></p>
	</div>
<?php } ?>

<?php $priorTo = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["shv"] . 'priorTo> ?resourceUri', 'template' => 'resource'));
if ( $priorTo != "" ) { ?>
	<p>Vorgänder von: <?php echo $priorTo; ?></p>
<?php } ?>

<?php $subsequentTo = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["shv"] . 'subsequentTo> ?resourceUri', 'template' => 'resource'));
if ( $subsequentTo != "" ) { ?>
	<p>Nachfolger von: <?php echo $subsequentTo; ?></p>
<?php } ?>

<?php if ( $born != "" ) { ?>
	<div class="">
		<h3 class="">Hier geborene Personen</h3>
		<?php echo $born; ?>
	</div>
<?php } ?>

<?php if ( $died != "" ) { ?>
	<div class="">
		<h3 class="">Hier verstorbene Personen</h3>
		<?php echo $died; ?>
	</div>
<?php } ?>

<?php if ( $bodies != "" ) { ?>
	<div class="">
		<h3 class="">Körperschaften in <?php echo $this->title ?></h3>
		<?php echo $bodies; ?>
	</div>
<?php } ?>
